# audio normalize
- af toggle "lavfi=[loudnorm=i=-18]";show-text "loudnorm enabled"
_ af toggle "dynaudnorm=g=5:f=250:r=0.9:p=0.5";show-text "dynaudnorm enabled"
= af toggle "acompressor=ratio=4,loudnorm";show-text "acompressor,loudnorm enabled"
+ af toggle "lavfi=[alimiter=10:1:1:5:8000]";show-text "alimiter enabled"
